# Generated by Django 4.1.5 on 2023-04-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='introduction',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='自己紹介文'),
        ),
    ]
