# Generated by Django 4.1.5 on 2023-04-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email_alter_customuser_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='自己紹介文'),
        ),
    ]
