# Generated by Django 4.1.5 on 2023-04-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='customer',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='サブスクリプションカスタマーID'),
        ),
    ]
