# Generated by Django 4.1.5 on 2023-04-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_kana',
            field=models.CharField(default='カナ', max_length=150, verbose_name='名(カナ)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_kana',
            field=models.CharField(default='カナ', max_length=150, verbose_name='姓(カナ)'),
            preserve_default=False,
        ),
    ]
