# Generated by Django 4.1.5 on 2023-04-02 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteGroup',
            new_name='FavoriteFolder',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'カテゴリ'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name_plural': 'お気に入り'},
        ),
        migrations.AlterModelOptions(
            name='favoritefolder',
            options={'verbose_name_plural': 'お気に入りフォルダ'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'フィードバック'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name_plural': '素材'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'プロジェクト'},
        ),
        migrations.AddField(
            model_name='favorite',
            name='favorite_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diy.favoritefolder', verbose_name='お気に入りフォルダ'),
        ),
    ]
