# Generated by Django 4.1.5 on 2023-04-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diy', '0002_rename_favoritegroup_favoritefolder_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name_plural': 'アルバム'},
        ),
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name_plural': 'コミュニティ'},
        ),
        migrations.AlterModelOptions(
            name='communitymessage',
            options={'verbose_name_plural': 'コミュニティメッセージ'},
        ),
        migrations.AlterModelOptions(
            name='communitytopic',
            options={'verbose_name_plural': 'コミュニティトピック'},
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='diy/project/thumbnail', verbose_name='サムネイル'),
        ),
    ]
