# Generated by Django 4.1.5 on 2023-04-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diy', '0003_alter_album_options_alter_community_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymessage',
            name='comment',
            field=models.TextField(verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='project',
            name='process',
            field=models.TextField(verbose_name='作業工程(作業内容)'),
        ),
    ]
