# Generated by Django 4.1.5 on 2023-04-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diy', '0004_alter_communitymessage_comment_alter_project_process'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
