# Generated by Django 4.1.5 on 2023-04-20 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('diy', '0007_infomation'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomation',
            name='site_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='サイトID'),
        ),
    ]
