# Generated by Django 4.1.5 on 2023-04-20 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('diy', '0008_infomation_site_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Infomation',
            new_name='Information',
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name_plural': '会社概要と利用規約'},
        ),
    ]
